packages:
  - '.'
  - 'apps/*'

onlyBuiltDependencies:
  - '@swc/core'
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  highlight.js@<9.18.2: '>=9.18.2'
  highlight.js@>=9.0.0 <10.4.1: '>=10.4.1'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
